import './globals.css';
import Navbar from './components/Navbar/index';
import Footer from './components/Footer/index';
// import Telegraf from '../public/telegraf-cdnfonts/'
import localFont from 'next/font/local'

export const metadata = {
  title: 'Omega',
  description: 'Generated by create next app',
}

const Telegraf = localFont({
  src: './font.otf',
  display: 'swap',
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={Telegraf.className}>
      <body>
        <Navbar /> 
        {children}
        <Footer />
      </body>
    </html>
  )
}
